### ISSUE TITLE
Welcome to 2015!

### ISSUE THREAD

**Issue by nmaxcom** [ryanbenson/Harvest#11]
So... a bit OT but you know...

![](http://i.imgur.com/qRoLqM5.png)

**Comment by ryanbenson** [comment]
Thanks for catching that :) I fixed it

![screen shot 2015-05-27 at 9 19 43 am](https://cloud.githubusercontent.com/assets/588599/7838263/89f065f2-0451-11e5-954a-0428a0f68ca6.png)

**Comment by nmaxcom** [comment]
No problem. Anywhere a date appears that changes (like that, or your age
etc) you should use a function so you can have piece of mind about it.
Thanks for Harvest btw, I don't know if I'll use it but looks good.

**Comment by ryanbenson** [comment]
True :) I forget sometimes, especially when I'm designing in-browser. And you're welcome. It suits some purposes but not all. I tried to keep it simple and changeable so it can transform to meet other needs. If you have any thoughts or suggestions, I'm happy to hear feedback.

**Comment by nmaxcom** [comment]
Well, just to ask a couple things: could you use something like html-ref
(dunno if this one is bugged ATM) to automatically produce the html files
with the updated references to the now concatenated files?

Also, I'm kind of at crossroads here in terms of webdev workflow. I've
always been an IDE fan, since I started C, C++, C#... and then web
development (phpstorm mostly, sometimes Brackets too for the live thing).
Can I ask what's your toolset and regular workflow?

Thanks Ryan.

**Comment by ryanbenson** [comment]
I'm not sure I completely understand your first point, so feel free to correct me if I don't interpret it properly. But at least with Harvest, when you're working on your SCSS and JS source files, they both automatically compile to all of your source files into styles.css and app.js, so those stay as your concatenated files which your HTML references. Since those filenames never change (I don't version or put unique names per compile), you don't need to adjust your HTML. The same is true when you deploy your changes, it compiles to the same filename. I hope that helps, if not let me know and I'll do my best :)

I understand where you're coming from :) I came from the opposite side, I trained as a UI designer and front-end, and adopted more back-end over time and now I'm more of a back-end programmer, so I understand the crossroads feeling. When I do front-end, I typically use Harvest because it suits most of my purposes and I mod it per-project where necessary (Browserify, etc).

I prefer to build my UI templates by themselves first without integrating them into my Rails or Node app until they're ready. And when modifications later come in, I do them in my templates silo first, then introduce the changes (HTML, css, js, etc) into the app from my templates. It helps me sort through all the features and browser testing without dealing with back-end issues or conflicts. So, I'll create a "template" folder in my project repo and work in there until I get all of my UI implementation done statically. And if the project is big enough, I'll create a remote environment to house my static HTML site to QA and review before the integration.

I use either Sublime Text or Brackets as my IDE with a bunch of plugins for linting, syntax, Emmet (awesome tool btw), etc. I don't use Bourbon or Compass as I don't use most of the features and it slows my gulp process down. I'll use Browserify when I need to do any non-trivial JS. Otherwise, I'll just download Harvest, run `npm install` to get the dev dependencies for gulp, and run `gulp` to start the development process, which watches all of my SCSS, HTML, JS, images files and re-builds and auto-reloads the page as I work. I've been doing that for the last couple years and it has really improved the quality and speed of my work.

Thanks!
