### ISSUE TITLE
just a compilation error from an else without an if statement

### ISSUE THREAD

**Issue by danvayn** [ryanbenson/Harvest#20]
https://github.com/ryanbenson/Harvest/blob/master/app/styles/scss/config/_mixins.scss#L84

**Comment by ryanbenson** [comment]
Thanks for letting me know about that. Turns out there were a couple mixins that were throwing errors. I updated the mixins.scss file. If you download the latest file (or the 1.3.5 package), let me know if it doesn't work. I tested it a couple times and it worked fine for me. Thanks again!

https://github.com/ryanbenson/Harvest/commit/979ee9dd68834744a273de73f82b6d9c93c333a0
